- name: log
  type: instant
  stepBlock:
    - identifier: firstMessageLogger
      properties:
        type: script
        params:
          scriptName: log
          inputs:
            message: ::workflow.input.firstMessage
    - identifier: secondMessageLogger
      properties:
        type: script
        params:
          scriptName: log
          inputs:
            message: ::workflow.input.secondMessage
    - identifier: conditionStep
      properties:
        type: conditional
        params:
          condition: "toto"
          stepBlock:
            - identifier: thirdMessageLogger
              properties:
                type: script
                params:
                  scriptName: log
                  inputs:
                    message: ::workflow.input.thirdMessage
    - identifier: loopStep
      properties:
        type: loop
        params:
          condition: "toto"
          maxAttempts: 3
          delayBetween: 1000
          stepBlock:
            - identifier: thirdMessageLoggerInLoop
              properties:
                type: script
                params:
                  scriptName: log
                  inputs:
                    message: looping
    - identifier: returnStep
      properties:
        type: return
        params:
          data:
            message1: ::workflow.input.firstMessage
            message2: ::workflow.input.secondMessage
            message3: ::workflow.input.thirdMessage
